# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev',
                'doc_host': 'https://yahan-ds.github.io',
                'git_url': 'https://github.com/yahan-ds/nbdev',
                'lib_path': 'nbdev'},
  'syms': {'nbdev.core': {'nbdev.core.foo': ('core.html#foo', 'nbdev/core.py')}}}
